name: MSBuild

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        arch: [x64, x86, ARM64]
        build_conf: [Debug, Release, Debug-Win11, Release-Win11]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore artifacts, or run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@v7.4
      with:
        vcpkgArguments: 'asio'
        vcpkgTriplet: '${{ matrix.arch }}-windows'
        vcpkgGitCommitId: '8b62f6fff30c4321945f1e498d85929285d7083a'

    - name: vcpkg integrate install
      shell: cmd
      run: |
        cd vcpkg && vcpkg.exe integrate install

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /m /p:Configuration=${{ matrix.build_conf }} /p:Platform="${{ matrix.arch }}" ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v2
      with:
        name: ovpn-dco_${{ matrix.arch }}_${{ matrix.build_conf }}
        path: |
          ${{ matrix.arch }}\${{matrix.build_conf}}\ovpn-dco\ovpn-dco.*
          ${{ matrix.arch }}\${{matrix.build_conf}}\ovpn-dco-cli.exe
