name: MSBuild

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: .

  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, x86, ARM64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore artifacts, or run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@v7.4
      with:
        vcpkgArguments: 'asio'
        vcpkgTriplet: '${{ matrix.arch }}-windows'
        vcpkgGitCommitId: '4474aba1e77be2d643eb684298b7d5479cad9a1f'

    - name: vcpkg integrate install
      shell: cmd
      run: |
        cd vcpkg && vcpkg.exe integrate install

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="${{ matrix.arch }}" ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          ${{ matrix.arch }}\${{env.BUILD_CONFIGURATION}}\ovpn-dco\ovpn-dco.*
          ${{ matrix.arch }}\${{env.BUILD_CONFIGURATION}}\ovpn-dco-cli.exe
